version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types: ["patch"]
