name: HTMLProofer/NPM Lint Build

on: [push, pull_request]

jobs:
  HTMLProofer:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Build
      run: bundle exec jekyll build
    - name: Run tests
      run: bundle exec htmlproofer ./_site

  npm-lint-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 20
    - run: npm install
    - run: npm run lint
    - run: npm run build
